---
title: "simulate_data_subproblem"
author: "Yunqi Yang"
date: "10/13/2021"
output: html_document
---

```{r  }

# load packages
library(mvtnorm)

#' Function to simulate a single component data with random weights. 
#' @param seed A random number
#' @param n Number of data points to simulate.
#' @param U The covariance matrix in the prior of size m \times m. 
#' @param V The residual covariance matrix of size m \times m. 
#' @return X: An n x m matrix in which each row is a draw from the 
#' single component model.
#' @importFrom mvtnorm rmvnorm
simulate_one_component <- function(seed, n, U, V) {
  
  set.seed(seed)
  
  # dimension of an obs. 
  m = nrow(U)
  
  # store simulated data
  X = matrix(NA, ncol = m, nrow = n)
  
  for (i in 1:n){
    # true class for obs. i 
    X[i, ] = rmvnorm(1, mean = rep(0,m), sigma = U + V)
  }
  p = runif(n)
  
  return(X)
}
```


```{r  }

seed = 1
n = 500
U = diag(2)
V = diag(2)
dat = simulate_one_component(seed, n, U, V)
save(dat, file = 'dat_one_comp.rds')

```

