#' @title Function Title Goes Here
#'
#' @description Description of function goes here.
#' 
#' @param X The n x m data matrix, in which each row is an
#'   m-dimensional observation.
#'
#' @param V An m x m matrix giving the initial estimate of the
#'   residual covariance matrix.
#'
#' @param n1 Describe input argument "n1" here.
#'
#' @param nf Describe input argument "nf" here.
#' 
#' @param U A list of length k giving initial estimates of the
#'   covariance matrices in the mixture-of-multivariate-normals prior;
#'   list element \code{U[[i]]} is the m x m covariance matrix for the
#'   ith mixture component. If not provided, the initial estimates are
#'   randomly generated by computing sample covariances on random
#'   subsets of the data \code{X}.
#' 
#' @param w A numeric vector of length k giving initial estimates of
#'   the prior mixture weights. All entries must be non-negative, but
#'   need not sum to 1; the mixture weights are automatically normalized
#'   to sum to 1. If not provided, the mixture weights are set to
#'   uniform.
#'
#' @examples
#'
#' library(mvtnorm)
#' set.seed(1)
#' V <- diag(2) + 1
#' X <- rmvt(1000,V,df = 4)
#' U <- list(fixed  = matrix(1,2,2),
#'           scaled = diag(2),
#'           rank1  = tcrossprod(c(1,2)),
#'           ed     = crossprod(matrix(rnorm(4),2,2)),
#'           teem   = crossprod(matrix(rnorm(4),2,2)))
#' attr(U$scaled,"covtype") <- "scaled"
#' attr(U$scaled,"update")  <- "ed"
#' attr(U$rank1,"covtype")  <- "rank1"
#' attr(U$fixed,"covtype")  <- "full"
#' attr(U$ed,"covtype")     <- "full"
#' attr(U$teem,"covtype")   <- "full"
#' fit0 <- ud_init(X,V,U = U)
#' 
#' @export
#'
ud_init <- function (X, V = diag(ncol(X)), n1 = 4, nf = 4,
                     U = list(indep = diag(ncol(X)),
                              iden = matrix(1,ncol(X),ncol(X))), w) {

  # Get the number of rows (n) and columns (m) of the data matrix,
  n <- nrow(X)
  m <- ncol(X)

  # Randomly initialize the rank-1 prior covariances.
  if (n1 > 0) {
    U1 <- vector("list",n1)
    names(U1) <- paste("rank1",1:n1,sep = "_")
    for (i in 1:n1) {
      U1[[i]] <- sim_r1(m)
      attr(U1[[i]],"covtype") <- "rank1"
    }
  } else
    U1 <- NULL

  # Randomly initialize the full prior covariances.
  if (nf > 0) {
    Uf <- vector("list",nf)
    names(Uf) <- paste0("full",1:nf)
    for (i in 1:nf) {
      # TO DO.
    }
  } else
    Uf <- NULL

  # TO DO: Process input argument U.
  
  # Combine the prior covariances into a single list.
  U <- c(U1,U)
  k <- length(U)

  # Set the default updates for the prior covariances when the updates
  # haven't already been chosen.
  # TO DO.
  
  # Check and process input w.
  if (missing(w))
    w <- rep(1/k,k)
  if (is.null(names(w)))
    names(w) <- names(U)
  
  # Add row and column names to the matrices.
  rownames(V) <- colnames(X)
  colnames(V) <- colnames(X)
  for (i in 1:k) {
    rownames(U[[i]]) <- colnames(X)
    colnames(U[[i]]) <- colnames(X)
  }
  
  # Finalize the output.
  fit <- list(V = V,U = U,w = w)
  class(fit) <- c("ud_fit","list")
  return(fit)
}

# TO DO: Explain here what this function does, and how to use it.
set_prior_covariance_updates <- function (U) {

}
