#' @title Function Title Goes Here
#'
#' @description Description of function goes here.
#' 
#' @param X The n x m data matrix, in which each row is an
#'   m-dimensional observation.
#'
#' @param V An m x m matrix giving the initial estimate of the
#'   residual covariance matrix.
#'
#' @param n1 Describe input argument "n1" here.
#'
#' @param nfull Describe input argument "nf" here.
#' 
#' @param U A list of length k giving initial estimates of the
#'   covariance matrices in the mixture-of-multivariate-normals prior;
#'   list element \code{U[[i]]} is the m x m covariance matrix for the
#'   ith mixture component. If not provided, the initial estimates are
#'   randomly generated by computing sample covariances on random
#'   subsets of the data \code{X}.
#' 
#' @param w A numeric vector of length k giving initial estimates of
#'   the prior mixture weights. All entries must be non-negative, but
#'   need not sum to 1; the mixture weights are automatically normalized
#'   to sum to 1. If not provided, the mixture weights are set to
#'   uniform.
#'
#' @examples
#'
#' library(mvtnorm)
#' set.seed(1)
#' n <- 1000
#' V <- diag(0.5,2) + 0.5
#' X <- rmvt(n,V,df = 4)
#' rownames(X) <- paste("s",1:n)
#' colnames(X) <- c("d1","d2")
#'
#' # Simplest invocation relying on default settings.
#' fit0 <- ud_init(X)
#'
#' # Override default U.
#' U1 <- matrix(0,2,2)
#' U2 <- diag(2)
#' U3 <- matrix(1,2,2)
#' attr(U1,"covtype") <- "full"; attr(U1,"covupdate") <- "fixed"
#' attr(U2,"covtype") <- "full"; attr(U2,"covupdate") <- "scaled"
#' attr(U3,"covtype") <- "full"; attr(U3,"covupdate") <- "teem"
#' fit1 <- ud_init(X,U = list(spike = U1,indep = U2,iden = U3))
#' 
#' @export
#'
ud_init <- function (X, V = diag(ncol(X)), n1 = 4, nfull = 4,
                     U = list(indep = diag(ncol(X)),
                              iden = matrix(1,ncol(X),ncol(X))), w) {

  # Get the number of rows (n) and columns (m) of the data matrix,
  n <- nrow(X)
  m <- ncol(X)

  # Randomly initialize the rank-1 prior covariances.
  if (n1 > 0) {
    U1 <- vector("list",n1)
    names(U1) <- paste("rank1",1:n1,sep = "_")
    for (i in 1:n1) {
      u <- simr1(m)
      attr(u,"covtype") <- "rank1"
      U1[[i]] <- u
    }
  } else
    U1 <- NULL

  # Randomly initialize the full prior covariances.
  if (nfull > 0) {
    Ufull <- vector("list",nfull)
    names(Ufull) <- paste0("full",1:nfull)
    for (i in 1:nfull) {
      u <- simfull(m)
      attr(u,"covtype") <- "full"
      Ufull[[i]] <- u
    }
  } else
    Ufull <- NULL

  # If the covariance type is not provided for an element of U, set to
  # be "full".
  nu <- length(U)
  if (nu > 0)
    for (i in 1:nu) {
      u <- U[[i]]
      if (is.null(attr(u,"covtype")))
        attr(u,"covtype") <- "full"
      U[[i]] <- u
    }
  
  # Combine the prior covariances into a single list.
  U <- c(U,U1,Ufull)
  k <- length(U)

  # Set the default updates for the prior covariances when the updates
  # haven't already been chosen.
  for (i in 1:k) {
    u <- U[[i]]
    covtype <- attr(u,"covtype")
    if (is.null(attr(u,"covupdate"))) {
      if (covtype == "rank1")
        attr(u,"covupdate") <- "rank1"
      else if (covtype == "full")
        attr(u,"covupdate") <- "ed"
      U[[i]] <- u
    }
  }
  
  # Check and process input w.
  if (missing(w))
    w <- rep(1/k,k)
  if (is.null(names(w)))
    names(w) <- names(U)
  
  # Add row and column names to the matrices.
  rownames(V) <- colnames(X)
  colnames(V) <- colnames(X)
  for (i in 1:k) {
    u <- U[[i]]
    rownames(u) <- colnames(X)
    colnames(u) <- colnames(X)
    U[[i]] <- u
  }
  
  # Finalize the output.
  fit <- list(V = V,U = U,w = w)
  class(fit) <- c("ud_fit","list")
  return(fit)
}
