#' @title Fit Empirical Bayes Multivariate Normal Means Model
#'
#' @description This function implements an empirical Bayes method for
#' fitting a multivariate normal means model. This method is closely
#' related to approaches for multivariate density deconvolution
#' (Sarkar \emph{et al}, 2018), so it can also be viewed as a method
#' for multivariate density deconvolution. In the multivariate normal
#' means model, each m-dimensional observation \eqn{x} is drawn from a
#' mixture of multivariate normals, \eqn{x ~ w_1 N(0, T_1) + ... + w_k
#' N(0, T_k)}, where \eqn{k} is the number of mixture components, the
#' \eqn{w_j}'s are the mixture weights, and each \eqn{T_j = S + U_j}
#' is a covariance matrix. This is the marginal density derived from a
#' model in which each \eqn{x} is multivariate normal with mean
#' \eqn{y} and covariance \eqn{S}, and the underlying, or "latent",
#' signal \eqn{y} is in turn modeled by a mixture prior in which each
#' mixture component \eqn{j} is multivariate normal with zero mean and
#' covariance matrix \eqn{S_j}. The "Extreme Deconvolution" (ED) model
#' (Bovy \emph{et al}, 2011) is a slight generalization of this
#' multivariate normal means model; the ED model allows for the
#' mixture components to have nonzero means, sample-specific residual
#' covariances, and it allows one to specify a linear projection of
#' the underlying signal onto the observed signal. Therefore, this
#' method also implements a useful special case of Extreme
#' Deconvolution.
#'
#' @details The multivariate normal means model is fit by
#' expectation-maximization (EM). Two EM variants are implemented: the
#' EM algorithm described by Bovy \emph{et al} (2011); and
#' \code{"teem"} (truncated eigenvalue expectation-maximization), in
#' which the M-step update for each covariance matrix \code{U[[j]]} is
#' solved by truncating the eigenvalues in a spectral decomposition of
#' the (unconstrained) maximimum likelihood estimate (MLE) of
#' \code{U[j]]}. The latter method provides greater freedom in the
#' updates for U, and is expected to yield better fits. The choice of
#' M-step update is specified by the \code{control$update.U}
#' optimization setting; continuing reading for details.
#'
#' Using this function requires some care; currently only minimal
#' argument checking is performed. See the documentation and examples
#' for guidance.
#' 
#' @param X The n x m data matrix, in which each row is an
#'   m-dimensional observation.
#'
#' @param k An integer 2 or greater specifying the number of
#'   components in the mixture-of-normals prior. This only needs to be
#'   provided if neither \code{U} nor \code{w} are provided.
#'
#' @param w A numeric vector of length k giving initial estimates of
#'   the prior mixture weights. All entries must be non-negative, but
#'   need not sum to 1; the mixture weights are automatically normalized
#'   to sum to 1. If not provided, the mixture weights are set to
#'   uniform.
#'
#' @param U A list of length k giving initial estimates of the
#'   covariance matrices in the mixture-of-multivariate-normals prior;
#'   list element \code{U[[i]]} is the m x m covariance matrix for the
#'   ith mixture component. If not provided, the initial estimates are
#'   randomly generated by computing sample covariances on random
#'   subsets of the data \code{X}.
#' 
#' @param S An m x m matrix giving the initial estimate of the
#'   residual covariance matrix.
#'
#' @param control A list of parameters controlling the behaviour of
#'   the model fitting algorithm. See \sQuote{Details}.
#'
#' @return A list object with the following elements:
#'
#' \item{w}{A vector containing the estimated prior mixture
#'   weights. When \code{control$update.w = FALSE}, this will be the
#'   same as \code{w} provided at input.}
#'
#' \item{U}{A list containing the estimated prior covariance matrices. When
#'   \code{control$update.U = FALSE}, this will be the same as \code{U}
#'   provided at input.}
#' 
#' \item{S}{The estimated residual covariance matrix. When
#'   \code{control$update.S = FALSE}, this will be the same as \code{S}
#'   provided at input.}
#'
#' \item{loglik}{The log-likelihood at the current settings of the
#'   model parameters, \code{w}, \code{U} and \item{S}; see
#'   \code{\link{loglik_mvebnm}}.}
#'   
#' \item{progress}{A data frame containing detailed information about
#'   the algorithm's progress. The columns of the data frame are:
#'   "iter", the iteration number; "loglik", the log-likelihood at the
#'   current estimates of the model parameters; "delta.w", the largest
#'   change in the mixture weights; "delta.u", the largest change in the
#'   prior covariance matrices; "delta.s", the largest change in the
#'   residual covariance matrix; and "timing", the elapsed time in
#'   seconds (recorded using \code{\link{proc.time}}).}
#' 
#' @references
#'
#' J. Bovy, D. W. Hogg and S. T. Roweis (2011). Extreme Deconvolution:
#' inferring complete distribution functions from noisy, heterogeneous
#' and incomplete observations. \emph{Annals of Applied Statistics},
#' \bold{5}, 1657–1677. doi:10.1214/10-AOAS439
#'
#' A. Sarkar, D. Pati, A. Chakraborty, B. K. Mallick and R. J. Carroll
#' (2018). Bayesian semiparametric multivariate density
#' deconvolution. \emph{Journal of the American Statistical
#' Association} \bold{113}, 401–416. doi:10.1080/01621459.2016.1260467
#'
#' J. Won, J. Lim, S. Kim and B. Rajaratnam
#' (2013). Condition-number-regularized covariance estimation.
#' \emph{Journal of the Royal Statistical Society, Series B} \bold{75},
#' 427–450. doi:10.1111/j.1467-9868.2012.01049.x
#' 
#' @useDynLib mvebnm
#'
#' @importFrom utils modifyList
#' @importFrom Rcpp evalCpp
#' 
#' @export
#' 
mvebnm <- function (X, k, w, U, S = diag(ncol(X)), control = list(),
                    verbose = TRUE) {
    
  # CHECK & PROCESS INPUTS
  # ----------------------
  # Check the input data matrix, X.
  X <- as.matrix(X)  
  if (!is.numeric(X))
    stop("Input argument \"X\" should be a numeric matrix")

  # Get the number of rows (n) and columns (m) of the data matrix,
  n <- nrow(X)
  m <- ncol(X)

  # Check and process input argument "k" specifying the number of
  # components in the mixture-of-normals prior.
  if (missing(k)) {
    if (missing(w) & missing(U))
      stop("At least one of \"k\", \"w\" and \"U\" should be provided")
    else if (missing(w))
      k <- length(U)
    else
      k <- length(w)
  }
  if (k < 2)
    stop("The number of prior mixture components (k) should be 2 or greater")

  # Check input argument "S" giving the initial estimate of the
  # residual covariance matrix.
  S <- as.matrix(S)
  if (!(nrow(S) == m & ncol(S) == m && is.semidef(S)))
    stop("Input argument \"S\" should be an m x m positive semi-definite ",
         "matrix, where m is the number of columns in \"X\"")

  # Check and process input argument "U" giving the initial estimates
  # of the prior covariance matrices. If this input is not provided,
  # the initial estimates are randomly generated by computing sample
  # covariances on random subsets of the data.
  if (missing(U))
    U <- generate.random.covariances(X,k)
  U <- lapply(U,as.matrix)
  if (!(all(sapply(U,is.matrix)) && verify.prior.covariances(U,S)))
    stop("Input argument \"U\" should be list in which each list element ",
         "U[[i]] is a (symmetric) positive semi-definite matrix, and",
         "S + U[[i]] is symmetric positive definite")
  mixture.labels <- names(U)
  U <- array(simplify2array(U),c(m,m,k))  

  # Check and process input argument "w" giving the initial estimates
  # of the mixture weights. Make sure the mixture weights are all
  # non-negative and sum to 1.
  if (missing(w))
    w <- rep(1,k)
  if (!(is.numeric(w) & length(w) == k & all(w >= 0)))
    stop("Input argument \"w\" should be a vector of length \"k\" ",
         "containing non-negative weights")
  w <- w/sum(w)

  # Check and process the optimization settings.
  control <- modifyList(mvebnm_control_default(),control,keep.null = TRUE)

  # Give an overview of the optimization settings.
  if (verbose) {
    cat(sprintf("Fitting %d-component mvebnm to %d x %d data matrix ",k,n,m))
    cat("with these settings:\n")
    cat(sprintf("Running max %d updates with ",control$maxiter))
    cat(sprintf("conv tol %0.1e ",control$tol))
    cat(sprintf("(mvebnm 0.1-46, \"%s\").\n",control$version))
    cat(sprintf("updates: w (mixture weights) = %s; ",control$update.w))
    cat(sprintf("U (prior cov) = %s; ",control$update.U))
    cat(sprintf("S (resid cov) = %s\n",control$update.S))
  }

  # RUN UPDATES
  # -----------
  if (verbose)
    cat("iter          log-likelihood |w - w'| |U - U'| |S - S'|\n")
  fit <- mvebnm_main_loop(X,w,U,S,control,verbose)

  # Output the parameters of the updated model (w, U, S), the
  # log-likelihood of the updated model (loglik), and a record of the
  # algorithm's progress over time (progress).
  fit$loglik <- loglik_mvebnm(X,fit$w,fit$U,fit$S,control$version)
  fit$U      <- array2list(fit$U)
  fit$S      <- drop(fit$S)
  for (i in 1:k) {
    rownames(fit$U[[i]]) <- colnames(X)
    colnames(fit$U[[i]]) <- colnames(X)
  }
  names(fit$w)    <- mixture.labels
  names(fit$U)    <- mixture.labels
  rownames(fit$S) <- colnames(X)
  colnames(fit$S) <- colnames(X)
  class(fit)      <- c("mvebnm_fit","list")
  return(fit)
}

# This implements the core part of mvebnm.
mvebnm_main_loop <- function (X, w, U, S, control, verbose) {

  # Get the number of components in the mixture prior.
  k <- length(w)

  # Set up data structures used in main loop.
  progress <- as.data.frame(matrix(as.numeric(NA),control$maxiter,6))
  names(progress) <- c("iter","loglik","delta.w","delta.u","delta.s","timing")
  progress[,"iter"] <- 1:control$maxiter

  # Iterate the EM updates.
  for (iter in 1:control$maxiter) {
      
    # Store the current estimates of the parameters.
    w0 <- w
    U0 <- U
    S0 <- S
    t1 <- proc.time()

    # E-step
    # ------
    # Compute the n x k matrix of posterior mixture assignment
    # probabilities given current estimates of the model parameters.
    P <- compute_posterior_probs(X,w,U,S,control$version)

    # M-step
    # ------
    # Update the mixture weights (w), if requested.
    if (control$update.w == "em") {
      w <- colSums(P)
      w <- w/sum(w)  
    }
    
    # Compute the M-step update for the residual covariance (S), if
    # relevant.
    if (control$update.S == "em") {
      #
      # TO DO.
      #
      Snew <- S
    }

    # Update the prior covariance matrices (U), if requested.
    if (control$update.U  == "em")
      U <- update_prior_covariance_ed(X,U,S,P,control$version)
    else if (control$update.U == "teem")
      U <- update_prior_covariance_teem(X,S,P,control$eps,control$version)

    # Apply the update for the residual covariance matrix, if
    # requested.
    if (control$update.S == "em")
      S <- Snew
    
    # Update the "progress" data frame with the log-likelihood and
    # other quantities, and report the algorithm's progress to the
    # console if requested.
    loglik <- loglik_mvebnm(X,w,U,S,control$version)
    dw     <- max(abs(w - w0))
    dS     <- max(abs(S - S0))
    dU     <- max(abs(U - U0))
    t2     <- proc.time()
    progress[iter,"loglik"]  <- loglik
    progress[iter,"delta.w"] <- dw 
    progress[iter,"delta.u"] <- dU 
    progress[iter,"delta.s"] <- dS 
    progress[iter,"timing"]  <- t2["elapsed"] - t1["elapsed"]
    if (verbose)
      cat(sprintf("%4d %+0.16e %0.2e %0.2e %0.2e\n",iter,loglik,dw,dU,dS))
    if (max(dw,dU,dS) < control$tol)
      break
  }

  # Output the parameters of the updated model (w, U, S) and a record
  # of the algorithm's progress over time ("progress").
  return(list(w = w,U = U,S = S,progress = progress[1:iter,]))
}

# Compute the n x k matrix of posterior mixture assignment
# probabilities given current estimates of the model parameters. This
# implements the "E step" in the EM algorithm for fitting the mvebnm
# model. These posterior computations are implemented in R (version =
# "R") and C++ (version = "Rcpp").
compute_posterior_probs <- function (X, w, U, S, version = c("Rcpp","R")) {
  version <- match.arg(version)
  if (version == "R")
    P <- compute_posterior_probs_helper(X,w,U,S)
  else if (version == "Rcpp")
    P <- compute_posterior_probs_rcpp(X,w,U,S);
  return(P)
}

# This implements the calculations for compute_posterior_probs.
#
#' @importFrom mvtnorm dmvnorm
compute_posterior_probs_helper <- function (X, w, U, S) {
      
  # Get the number of samples (n) and the number of components in the
  # mixture prior (k).
  n <- nrow(X)
  k <- length(w)

  # Compute the log-probabilities, stored in an n x k matrix.
  P <- matrix(0,n,k)
  for (i in 1:k)
    P[,i] = log(w[i]) + dmvnorm(X,sigma = S + U[,,i],log = TRUE)

  # Normalize the probabilities so that each row of P sums to 1.
  return(softmax(P))
}

# Perform an M-step update for the prior covariance matrices using the
# update formla derived in Bovy et al (2011). The calculations are
# implemented in both R (version = "R") and C++ (version = "Rcpp").
update_prior_covariance_ed <- function (X, U, S, P, version = c("Rcpp","R")) {
  version <- match.arg(version)
  U0 <- U
  if (version == "R") {
    k <- ncol(P)
    for (i in 1:k)
      U[,,i] <- update_prior_covariance_ed_helper(X,U[,,i],S,P[,i])
  } else if (version == "Rcpp")
    U <- update_prior_covariances_ed_rcpp(X,U,S,P)
  return(U)
}

# Perform an M-step update for the prior covariance matrices using the
# eigenvalue-truncation technique described in Won et al (2013). The
# calculations are implemented in both R (version = "R") and C++
# (version = "Rcpp").
update_prior_covariance_teem <- function (X, S, P, e,
                                          version = c("Rcpp","R")) {
  version <- match.arg(version)
  if (version == "R") {
    m <- ncol(X)
    k <- ncol(P)
    U <- array(0,dim = c(m,m,k))
    for (i in 1:k)
      U[,,i] <- update_prior_covariance_teem_helper(X,S,P[,i],e)
  } else if (version == "Rcpp")
    U <- update_prior_covariances_teem_rcpp(X,S,P,e)
  return(U)
}

# Perform an M-step update for the residual covariance matrix, S.
update_resid_covariance <- function (X, U, S, P) {
  n <- nrow(X)
  m <- ncol(X)
  S <- matrix(0,m,m)
  for (i in 1:n) {
    x   <- X[i,]
    out <- compute_posterior_mvtnorm_mix(x,P[i,],U,S)
    mu1 <- out$mu1
    S1  <- out$s1
    S   <- S + S1 + tcrossprod(x - mu1)
  }
  return(S/n)
}

# Perform an M-step update for one of the prior covariance matrices
# using the update formula derived in Bovy et al (2011). Here, p is a
# vector, with one entry per row of X, giving the posterior assignment
# probabilities for the mixture component being updated.
update_prior_covariance_ed_helper <- function (X, U, S, p) {
  T <- S + U
  B <- solve(T,U)
  Y <- crossprod((sqrt(p/sum(p)) * X) %*% B)
  return(U - U %*% B + Y)
}

# Perform an M-step update for one of the prior covariance matrices
# using the eigenvalue-truncation technique described in Won et al
# (2013). Input p is a vector, with one entry per row of X, giving
# the posterior assignment probabilities for the mixture components
# being updated.
update_prior_covariance_teem_helper <- function (X, S, p, e) {

  # Transform the data so that the residual covariance is I, then
  # compute the maximum-likelhood estimate (MLE) for T = U + I.
  R <- chol(S)
  T <- crossprod((sqrt(p/sum(p))*X) %*% solve(R))
  
  # Find U maximizing the expected complete log-likelihood subject to
  # U being positive definite. This update for U is based on the fact
  # that the covariance matrix that minimizes the likelihood subject
  # to the constraint that U is positive definite is obtained by
  # truncating the eigenvalues of T = U + I less than 1 to be 1; see
  # Won et al (2013), p. 434, the sentence just after equation (16).
  U <- shrink.cov(T,e)

  # Recover the solution for the original (untransformed) data.
  return(t(R) %*% U %*% R)
}

# Suppose x is drawn from a multivariate normal distribution with mean
# z and covariance S, and z is drawn from a mixture of multivariate
# normals, each with zero mean, covariance V[,,i] and weight w[i].
# Return the posterior mean (mu1) and covariance (S1) of z. Note that
# input w1 must be the vector of *posterior* mixture weights.
compute_posterior_mvtnorm_mix <- function (x, w1, V, S) {
  m   <- length(m)
  k   <- length(V)
  mu1 <- rep(0,m)
  S1  <- matrix(0,m,m)
  for (i in 1:k) {
    w   <- w1[i]
    out <- compute_posterior_mvtnorm(V[,,i],S)
    mu  <- out$mu1
    S   <- out$S1
    mu1 <- mu1 + w*mu
    S1  <- S1 + w*(S + tcrossprod(mu))
  }
  S1 <- S1 - tcrossprod(mu1)
  return(list(mu1 = mu1,S1 = S1))
}

# Suppose x is drawn from a multivariate normal distribution with mean
# z and covariance S, and z is drawn from a multivariate normal
# distribution with mean zero and covariance V. Return the posterior
# mean (mu1) and covariance (S1) of z.
compute_posterior_mvtnorm <- function (V, S) {
  # TO DO.
}

#' @rdname mvebnm
#'
#' @export
#' 
mvebnm_control_default <- function()
  list(update.U = "teem",  # One of "em", "teem" or "none".
       update.w = "em",    # One or "em" or "none".
       update.S = "em",    # One of "em" or "none".
       version  = "Rcpp",  # One of "R" or "Rcpp".
       maxiter  = 1000,
       eps      = 1e-15,
       tol      = 1e-6)
