#' @title Fit Empirical Bayes Multivariate Normal Means Model
#'
#' @description This function implements an empirical Bayes method for
#' fitting a multivariate normal means model. This method is closely
#' related to approaches for multivariate density deconvolution
#' (Sarkar \emph{et al}, 2018), so it can also be viewed as a method
#' for multivariate density deconvolution. In the multivariate normal
#' means model, each m-dimensional observation \eqn{x} is drawn from a
#' mixture of multivariate normals, \eqn{x ~ w_1 N(0, T_1) + ... + w_k
#' N(0, T_k)}, where \eqn{k} is the number of mixture components, the
#' \eqn{w_j}'s are the mixture weights, and each \eqn{T_j = S + U_j} is
#' a covariance matrix. This is the marginal density derived from a
#' model in which each \eqn{x} is multivariate normal with mean
#' \eqn{y} and covariance \eqn{S}, and the underlying, or "latent",
#' signal \eqn{y} is in turn modeled by a mixture prior in which each
#' mixture component \eqn{j} is multivariate normal with zero mean and
#' covariance matrix \eqn{S_j}. The "Extreme Deconvolution" model
#' (Bovy \emph{et al}, 2011) is a slight generalization of this
#' multivariate normal means model; it allows for the mixture
#' components to have nonzero means, and it allows one to specify a
#' linear projection of the underlying signal onto the observed
#' signal. Therefore, this method also implements a useful special
#' case of Extreme Deconvolution.
#'
#' @details The multivariate normal means model is fit by
#' expectation-maximization (EM). Two EM variants are implemented: the
#' EM algorithm described by Bovy \emph{et al} (2011); and
#' \code{"teem"} (truncated eigenvalue expectation-maximization), in
#' which the M-step update for each covariance matrix \code{U[[j]]} is
#' solved by truncating the eigenvalues in a spectral decomposition of
#' the (unconstrained) maximimum likelihood estimate (MLE) of
#' \code{U[j]]}. The latter method provides greater freedom in the
#' updates for U, and is expected to yield better fits. The choice of
#' M-step update is specified by the \code{control$update.U}
#' optimization setting; continuing reading for details.
#'
#' Using this function requires some care; currently only minimal
#' argument checking is performed. See the documentation and examples
#' for guidance.
#' 
#' @param X The n x m data matrix, in which each row is an
#'   m-dimensional observation.
#'
#' @param k An integer 2 or greater specifying the number of
#'   components in the mixture-of-normals prior. This only needs to be
#'   provided if neither \code{U} nor \code{w} are provided.
#'
#' @param w A numeric vector of length k giving initial estimates of
#'   the prior mixture weights. All entries must be non-negative, but
#'   need not sum to 1; the mixture weights are automatically normalized
#'   to sum to 1. If not provided, the mixture weights are set to
#'   uniform.
#'
#' @param U A list of length k giving initial estimates of the
#'   covariance matrices in the mixture-of-multivariate-normals prior;
#'   list element \code{U[[i]]} is the m x m covariance matrix for the
#'   ith mixture component. If not provided, the initial estimates are
#'   randomly generated by computing sample covariances on random
#'   subsets of the data \code{X}.
#' 
#' @param S An m x m matrix giving the initial estimate of the
#'   residual covariance matrix.
#'
#' @param control A list of parameters controlling the behaviour of
#'   the model fitting algorithm. See \sQuote{Details}.
#'
#' @return A list object with the following elements:
#'
#' \item{item1}{Describe "item1" here.}
#' 
#' \item{item2}{Describe "item2" here.}
#' 
#' @references
#'
#' J. Bovy, D. W. Hogg and S. T. Roweis (2011). Extreme Deconvolution:
#' inferring complete distribution functions from noisy, heterogeneous
#' and incomplete observations. \emph{Annals of Applied Statistics},
#' \bold{5}, 1657–1677. doi:10.1214/10-AOAS439
#'
#' A. Sarkar, D. Pati, A. Chakraborty, B. K. Mallick and R. J. Carroll
#' (2018). Bayesian semiparametric multivariate density
#' deconvolution. \emph{Journal of the American Statistical
#' Association} \bold{113}, 401–416. doi:10.1080/01621459.2016.1260467
#'
#' J. Won, J. Lim, S. Kim and B. Rajaratnam
#' (2013). Condition-number-regularized covariance estimation.
#' \emph{Journal of the Royal Statistical Society, Series B} \bold{75},
#' 427–450. doi:10.1111/j.1467-9868.2012.01049.x
#' 
#' @useDynLib mvebnm
#'
#' @importFrom utils modifyList
#' @importFrom Rcpp evalCpp
#' 
#' @export
#' 
# Input parameters:
# U: initial estimates for covariance matrices, list of m by m matrices.
# eps: we usually specify a small number for eps, say 1e-8, used to resolve numerical issues.
# maxiter: maximum number of iterations
# tol: criteria for convergence
#
mvebnm <- function (X, k, w, U, S = diag(ncol(X)), control = list(),
                    verbose = TRUE) {
    
  # CHECK & PROCESS INPUTS
  # ----------------------
  # Check the input data matrix, X.
  if (!(is.numeric(X) & is.matrix(X)))
    stop("Input argument \"X\" should be a numeric matrix")

  # Get the number of rows (n) and columns (m) of the data matrix,
  n <- nrow(X)
  m <- ncol(X)

  # Check and process input argument "k" specifying the number of
  # components in the mixture-of-normals prior.
  if (missing(k)) {
    if (missing(w) & missing(U))
      stop("At least one of \"k\", \"w\" and \"U\" should be provided")
    else if (missing(w))
      k <- length(U)
    else
      k <- length(w)
  }
  if (k < 2)
    stop("The number of prior mixture components (k) should be 2 or greater")
  
  # Check input argument "S" giving the initial estimate of the
  # residual covariance matrix.
  if (!(is.matrix(S) & nrow(S) == m & ncol(S) == m && is.semidef(S)))
    stop("Input argument \"S\" should be an m x m positive semi-definite ",
         "matrix, where m is the number of columns in \"X\"")

  # Check and process input argument "U" giving the initial estimates
  # of the prior covariance matrices. If this input is not provided,
  # the initial estimates are randomly generated by computing sample
  # covariances on random subsets of the data.
  if (missing(U))
    U <- generate.random.covariances(X,k)
  if (!(is.list(U) &&
        all(sapply(U,is.matrix)) &&
        verify.prior.covariances(U,S)))
    stop("Input argument \"U\" should be list in which each list element ",
         "U[[i]] is a (symmetric) positive semi-definite matrix, and",
         "S + U[[i]] is symmetric positive definite")
  mixture.labels <- names(U)
  
  # Check and process input argument "w" giving the initial estimates
  # of the mixture weights. Make sure the mixture weights are all
  # non-negative and sum to 1.
  if (missing(w))
    w <- rep(1,k)
  if (!(is.numeric(w) & length(w) == k & all(w >= 0)))
    stop("Input argument \"w\" should be a vector of length \"k\" ",
         "containing non-negative weights")
  w <- w/sum(w)

  # Check and process the optimization settings.
  control <- modifyList(mvebnm_control_default(),control,keep.null = TRUE)

  # Give an overview of the optimization settings.
  if (verbose) {
    cat(sprintf("Fitting %d-component mvebnm to %d x %d data matrix ",k,n,m))
    cat("with these settings:\n")
    cat(sprintf("Running max %d updates with ",control$maxiter))
    cat(sprintf("conv tol %0.1e ",control$tol))
    cat(sprintf("(mvebnm 0.1-22, \"%s\").\n",control$version))
    cat(sprintf("updates: w (mixture weights) = %s; ",control$update.w))
    cat(sprintf("U (prior cov) = %s; ",control$update.U))
    cat(sprintf("S (resid cov) = %s\n",control$update.S))
  }
  
  # RUN UPDATES
  # -----------
  if (verbose)
    cat("iter          log-likelihood |w - w'| |U - U'| |S - S'|\n")
  fit <- mvebnm_main_loop(X,w,U,S,control,verbose)
  
  # Output the parameters of the updated model (w, U, S), the
  # log-likelihood of the updated model (loglik), and a record of the
  # algorithm's progress over time (progress).
  fit$loglik <- loglik_mvebnm(X,fit$w,fit$U,fit$S,control$version)
  for (i in 1:k) {
    rownames(fit$U[[i]]) <- colnames(X)
    colnames(fit$U[[i]]) <- colnames(X)
  }
  names(fit$w)    <- mixture.labels
  names(fit$U)    <- mixture.labels
  rownames(fit$S) <- colnames(X)
  colnames(fit$S) <- colnames(X)
  class(fit)      <- c("mvebnm_fit","list")
  return(fit)
}

# This implements the core part of mvebnm.
mvebnm_main_loop <- function (X, w, U, S, control, verbose) {

  # Get the number of components in the mixture prior.
  k <- length(U)
    
  # Set up data structures used in main loop.
  progress <- as.data.frame(matrix(as.numeric(NA),control$maxiter,6))
  names(progress) <- c("iter","loglik","delta.w","delta.U","delta.S","timing")
  progress[,"iter"] <- 1:control$maxiter

  # Iterate the EM updates.
  for (iter in 1:control$maxiter) {
      
    # Store the current estimates of the parameters.
    w0 <- w
    U0 <- U
    S0 <- S
    t1 <- proc.time()

    # E-step
    # ------
    # Compute the n x k matrix of posterior mixture assignment
    # probabilities given current estimates of the model parameters.
    P <- compute_posterior_probs(X,w,U,S,control$version)

    # M-step
    # ------
    # Update the mixture weights (w), if requested.
    if (control$update.w == "em")
      w <- colMeans(P)
    
    # Update the prior covariance matrices (U), if requested.
    if (control$update.U  == "em") {
      # TO DO.
    } else if (control$update.U == "teem")
      U <- update_prior_covariances(X,S,P,control$eps,control$version)
    
    
    # Update the residual covariance (S), if requested.
    if (control$update.S == "em") {
      # TO DO.
    }
    
    # Update the "progress" data frame with the log-likelihood and
    # other quantities, and report the algorithm's progress to the
    # console if requested.
    loglik <- loglik_mvebnm(X,w,U,S,control$version)
    dw     <- max(abs(w - w0))
    dS     <- max(abs(S - S0))
    dU     <- 0
    for (i in 1:k)
      dU <- max(dU,max(abs(U[[i]] - U0[[i]])))
    t2 <- proc.time()
    progress[iter,"loglik"]  <- loglik
    progress[iter,"delta.w"] <- dw 
    progress[iter,"delta.U"] <- dU 
    progress[iter,"delta.S"] <- dS 
    progress[iter,"timing"]  <- t2["elapsed"] - t1["elapsed"]
    if (verbose)
      cat(sprintf("%4d %+0.16e %0.2e %0.2e %0.2e\n",iter,loglik,dw,dU,dS))
    if (max(dw,dU,dS) < control$tol)
      break
  }

  # Output the parameters of the updated model (w, U, S) and a record
  # of the algorithm's progress over time ("progress").
  return(list(w = w,U = U,S = S,progress = progress[1:iter,]))
}

# Compute the n x k matrix of posterior mixture assignment
# probabilities given current estimates of the model parameters. These
# posterior computations are implemented in R (version = "R") and C++
# (version = "Rcpp").
compute_posterior_probs <- function (X, w, U, S, version = c("Rcpp","R")) {
  version <- match.arg(version)
  if (version == "Rcpp") {
    # TO DO.
  } else if (version == "R")
    P <- compute_posterior_probs_helper(X,w,U,S)    
  return(P)
}

# This implements the calculations for compute_posterior_probs.
#
#' @importFrom mvtnorm dmvnorm
compute_posterior_probs_helper <- function (X, w, U, S) {
      
  # Get the number of samples (n) and the number of components in the
  # mixture prior (k).
  n <- nrow(X)
  k <- length(U)

  # Compute the log-probabilities, stored in an n x k matrix.
  P <- matrix(0,n,k)
  for (i in 1:k)
    P[,i] = log(w[i]) + dmvnorm(X,sigma = S + U[[i]],log = TRUE)

  # Normalize the probabilities so that each row of P sums to 1.
  return(normalizelogweights(P))
}

# TO DO: Explain here what this function does, and how to use it.
update_prior_covariances <- function (X, S, P, e, version = c("Rcpp","R")) {
  version <- match.arg(version)
  if (version == "Rcpp") {
    # TO DO.
  } else if (version == "R") {
    k <- ncol(P)
    U <- vector("list",k)
    for (i in 1:k)
      U[[i]] <- update_prior_covariance(X,S,P[,i],e)
  }
  return(U)
}

# TO DO: Explain here what this function does, and how to use it.
update_prior_covariance <- function (X, S, p, e) {
    
  # Transform the data so that the residual covariance is I, then
  # compute the maximum-likelhood estimate (MLE) for T = U + I.
  R <- chol(S)
  T <- crossprod((sqrt(p/sum(p)) * X) %*% solve(R))
  
  # Find U maximizing the expected complete log-likelihood subject to
  # U being positive definite. This update for U is based on the fact
  # that the covariance matrix that minimizes the likelihood subject
  # to the constraint that U is positive definite is obtained by
  # truncating any eigenvalues of T = U + I less than 1 to be 1; see
  # Won et al (2013), p. 434, the sentence just after equation (16).
  U <- shrink.cov(T,e)
  
  # Recover the solution for the original (untransformed) data.
  return(t(R) %*% U %*% R)
}

#' @rdname mvebnm
#'
#' @export
#' 
mvebnm_control_default <- function()
  list(update.U = "teem",  # One of "em", "teem" or "none".
       update.w = "em",    # One or "em" or "none".
       update.S = "em",    # One of "em" or "none".
       version  = "Rcpp",  # One of "R" or "Rcpp".
       maxiter  = 1000,
       eps      = 1e-15,
       tol      = 1e-6)
