# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldmvnorm_rcpp <- function(x, S) {
    .Call('_mvebnm_ldmvnorm_rcpp', PACKAGE = 'mvebnm', x, S)
}

fit_teem_rcpp <- function(X_mat, w_vec, U_3d, maxiter, converge_tol, eigen_tol, verbose) {
    .Call('_mvebnm_fit_teem_rcpp', PACKAGE = 'mvebnm', X_mat, w_vec, U_3d, maxiter, converge_tol, eigen_tol, verbose)
}

