# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_posterior_probs_iid_rcpp <- function(X, w, U, V) {
    .Call('_udr_compute_posterior_probs_iid_rcpp', PACKAGE = 'udr', X, w, U, V)
}

compute_posterior_probs_general_rcpp <- function(X, w, U, V) {
    .Call('_udr_compute_posterior_probs_general_rcpp', PACKAGE = 'udr', X, w, U, V)
}

update_prior_covariances_ed_rcpp <- function(X, U, V, P) {
    .Call('_udr_update_prior_covariances_ed_rcpp', PACKAGE = 'udr', X, U, V, P)
}

update_prior_covariances_teem_rcpp <- function(X, V, P, minval) {
    .Call('_udr_update_prior_covariances_teem_rcpp', PACKAGE = 'udr', X, V, P, minval)
}

update_resid_covariance_rcpp <- function(X, U, V, P) {
    .Call('_udr_update_resid_covariance_rcpp', PACKAGE = 'udr', X, U, V, P)
}

loglik_ud_iid_rcpp <- function(X, w, U, V) {
    .Call('_udr_loglik_ud_iid_rcpp', PACKAGE = 'udr', X, w, U, V)
}

loglik_ud_general_rcpp <- function(X, w, U, V) {
    .Call('_udr_loglik_ud_general_rcpp', PACKAGE = 'udr', X, w, U, V)
}

